# Generated by Django 4.0 on 2024-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='remote_ip',
            field=models.CharField(max_length=64),
        ),
    ]
